# Dockerfile to create Mageia linux 7 (cauldron) base images
# Create base image with mkimage-dnf.sh script
#

FROM scratch
MAINTAINER "JMiahMan" <jmiahman@unity-linux.org>
ADD rootfs-systemd.tar.xz /
